login: &login
  adapter: mysql
  username: root
  password: 
  host: localhost
  encoding: utf8

development:
  <<: *login
  database: myipaddresses_dev

test: &test
  <<: *login
  database: myipaddresses_test

production:
  <<: *login
  database: myipaddresses_prod

cucumber:
  <<: *test